preferred_endpoint: openai

endpoints:
  anthropic:
    api_key_env: NLWEB_ANTHROPIC_API_KEY
    llm_type: anthropic
    models:
      high: claude-3-7-sonnet-latest
      low: claude-3-5-haiku-latest

  gemini:
    api_key_env: GEMINI_API_KEY
    llm_type: gemini
    models:
      high: gemini-2.0-flash
      low: gemini-2.0-flash

  openai:
    api_key_env: OPENAI_API_KEY
    api_endpoint_env: OPENAI_ENDPOINT
    llm_type: openai
    models:
      high: gpt-5.1
      low: gpt-4o-mini
